### ISSUE TITLE
Cosmwasm: Folder location issues

### ISSUE THREAD

**Issue by ValarDragon** [osmosis-labs/osmosis#2354]
## Background

We currently have a few problems with the cosmwasm folder path location that we should resolve:

* `osmosisd export` only works if done in your `.osmosisd` folder
* Full nodes will crash if `.osmosisd/wasm` folder does not exist
* `wasm` folder should be in `data/wasm` to make it more standard with other chain-data

## Suggested Design

* Make `wasm` folder be in `.osmosisd/data/wasm` by default
* If folder at `.osmosisd/data/wasm` doesn't exist but it does exist at `.osmosisd/wasm` , use the latter folder
* If neither exist, make folder get created at `.osmosisd/data/wasm` (to help solve problems for syncing nodes)
* Make `osmosisd export` read from correct absolute path for wasm. (not sure wwhat happened here)

## Acceptance Criteria

- [ ] `osmosisd export` works when executed from any directory
- [ ] We believe that the code creates the wasm folder if it doesn't exist.

**Comment by vuong177** [comment]
@ValarDragon I run  `osmosisd export` for export my local testnet but got this err :
```
Error: error exporting state: json: error calling MarshalJSON for type json.RawMessage: unexpected end of JSON input
```
I run this cmd in `.osmosisd` folder but got same problem. Is it another issue?

**Comment by czarcas7ic** [comment]
@vuong177 export wont work due to ICA issue. If you use this branch you can get export to work: [adam/v11-ica-export-patch](https://github.com/osmosis-labs/osmosis/tree/adam/v11-ica-export-patch)

**Comment by vuong177** [comment]
@czarcas7ic thank you

**Comment by faddat** [comment]
hey guys, on Juno, we had the smae issue.  Finding:

1) state sync
2) stop the node
3) export

^ ought to work

**Comment by czarcas7ic** [comment]
@faddat the issue in our case was someone on mainnet had utilized ICA when it wasn't properly initialized on our end (will be in v12). So when we tried to state export it doesn't know how to handle ICA messages (my branch just filters out ICA messages from state exports until v12)

Thanks for the heads up though, will keep this in mind if it continues to be a problem come v12!

**Comment by ValarDragon** [comment]
The export problem at least is now fixed

**Comment by anhductn2001** [comment]
I still can't export state after set up a node on mainnet v13.1 by [get.osmosis.zone]([url](url)) tool.

**Comment by czarcas7ic** [comment]
Can you show the error? Make sure you run the state export command from the .osmosisd folder as well

**Comment by anhductn2001** [comment]
`Error: error exporting state: json: error calling MarshalJSON for type json.RawMessage: unexpected end of JSON input`
Yea, I tried to run command in the .osmosisd folder

**Comment by ValarDragon** [comment]
I believe this was fixed
