### ISSUE TITLE
Note to Validators

### ISSUE THREAD

**Issue by faddat** [osmosis-labs/osmosis#520]
Hi,

I'm operating a relayer. If you are operating a validator, it is very important that you:

```
systemctl enable systemd-timesyncd
systemctl start systemd-timesyncd
```

please.

If you do not, there are time drift errors, and well, the Hermes default of five seconds is really pretty generous.  We should be less than five seconds apart.

**Comment by faddat** [comment]
```
Oct 12 09:04:56 archive hermes[741991]:    0: GRPC call return error status status: InvalidArgument, message: "failed to execute message; message index: 0: cannot update client with ID 07-tendermint-1457: failed to verify header: invalid header: new header has a time from the future 2021-10-12 07:04:50.046283195 +0000 UTC (now: 2021-10-12 07:04:43.209109453 +0000 UTC; max clock drift: 5s): invalid request", details: [], metadata: MetadataMap { headers: {"content-type": "application/grpc"} }
```

**Comment by ValarDragon** [comment]
Per that ibc-rs issue, my reading is that increasing this time moderately has ~no risks / downsides. Its mostly about tolerating clock drift on smaller scales. (Or at least thats my reading, I am admittedly horribly under-informed here)

**Comment by ValarDragon** [comment]
Whats the sitaution like now? I think we're going to be more able to get this resolved via pinned announcements on the discord/telegram. We can coordinate if you'd like to make a discord announcement

**Comment by faddat** [comment]
This is still happening, but less often, and may have been related to fee calculation in hermes..... but the same thing would happen with the Go relayer, too.
